// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: server/store/store.proto

package store

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CA_Status int32

const (
	CA_Active   CA_Status = 0
	CA_Expired  CA_Status = 1
	CA_Inactive CA_Status = 2
	CA_Next     CA_Status = 3
)

// Enum value maps for CA_Status.
var (
	CA_Status_name = map[int32]string{
		0: "Active",
		1: "Expired",
		2: "Inactive",
		3: "Next",
	}
	CA_Status_value = map[string]int32{
		"Active":   0,
		"Expired":  1,
		"Inactive": 2,
		"Next":     3,
	}
)

func (x CA_Status) Enum() *CA_Status {
	p := new(CA_Status)
	*p = x
	return p
}

func (x CA_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CA_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_server_store_store_proto_enumTypes[0].Descriptor()
}

func (CA_Status) Type() protoreflect.EnumType {
	return &file_server_store_store_proto_enumTypes[0]
}

func (x CA_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CA_Status.Descriptor instead.
func (CA_Status) EnumDescriptor() ([]byte, []int) {
	return file_server_store_store_proto_rawDescGZIP(), []int{0, 0}
}

type CA struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NetworkName   string                 `protobuf:"bytes,1,opt,name=networkName,proto3" json:"networkName,omitempty"`
	PublicKey     []byte                 `protobuf:"bytes,10,opt,name=publicKey,proto3" json:"publicKey,omitempty"`
	PrivateKey    []byte                 `protobuf:"bytes,11,opt,name=privateKey,proto3" json:"privateKey,omitempty"`
	Sha256Sum     string                 `protobuf:"bytes,12,opt,name=sha256sum,proto3" json:"sha256sum,omitempty"`
	Status        CA_Status              `protobuf:"varint,20,opt,name=status,proto3,enum=store.CA_Status" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CA) Reset() {
	*x = CA{}
	mi := &file_server_store_store_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CA) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CA) ProtoMessage() {}

func (x *CA) ProtoReflect() protoreflect.Message {
	mi := &file_server_store_store_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CA.ProtoReflect.Descriptor instead.
func (*CA) Descriptor() ([]byte, []int) {
	return file_server_store_store_proto_rawDescGZIP(), []int{0}
}

func (x *CA) GetNetworkName() string {
	if x != nil {
		return x.NetworkName
	}
	return ""
}

func (x *CA) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *CA) GetPrivateKey() []byte {
	if x != nil {
		return x.PrivateKey
	}
	return nil
}

func (x *CA) GetSha256Sum() string {
	if x != nil {
		return x.Sha256Sum
	}
	return ""
}

func (x *CA) GetStatus() CA_Status {
	if x != nil {
		return x.Status
	}
	return CA_Active
}

type EnrollmentToken struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	NetworkName   string                 `protobuf:"bytes,2,opt,name=networkName,proto3" json:"networkName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollmentToken) Reset() {
	*x = EnrollmentToken{}
	mi := &file_server_store_store_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollmentToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollmentToken) ProtoMessage() {}

func (x *EnrollmentToken) ProtoReflect() protoreflect.Message {
	mi := &file_server_store_store_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollmentToken.ProtoReflect.Descriptor instead.
func (*EnrollmentToken) Descriptor() ([]byte, []int) {
	return file_server_store_store_proto_rawDescGZIP(), []int{1}
}

func (x *EnrollmentToken) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *EnrollmentToken) GetNetworkName() string {
	if x != nil {
		return x.NetworkName
	}
	return ""
}

type EnrollmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fingerprint   []byte                 `protobuf:"bytes,1,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	Created       *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created,proto3" json:"created,omitempty"`
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	NetworkName   string                 `protobuf:"bytes,4,opt,name=networkName,proto3" json:"networkName,omitempty"`
	CsrPEM        string                 `protobuf:"bytes,5,opt,name=csrPEM,proto3" json:"csrPEM,omitempty"`
	ClientIP      string                 `protobuf:"bytes,6,opt,name=clientIP,proto3" json:"clientIP,omitempty"`
	Groups        []string               `protobuf:"bytes,7,rep,name=groups,proto3" json:"groups,omitempty"`
	Name          string                 `protobuf:"bytes,8,opt,name=name,proto3" json:"name,omitempty"`
	RequestedIP   string                 `protobuf:"bytes,9,opt,name=requestedIP,proto3" json:"requestedIP,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollmentRequest) Reset() {
	*x = EnrollmentRequest{}
	mi := &file_server_store_store_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollmentRequest) ProtoMessage() {}

func (x *EnrollmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_store_store_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollmentRequest.ProtoReflect.Descriptor instead.
func (*EnrollmentRequest) Descriptor() ([]byte, []int) {
	return file_server_store_store_proto_rawDescGZIP(), []int{2}
}

func (x *EnrollmentRequest) GetFingerprint() []byte {
	if x != nil {
		return x.Fingerprint
	}
	return nil
}

func (x *EnrollmentRequest) GetCreated() *timestamppb.Timestamp {
	if x != nil {
		return x.Created
	}
	return nil
}

func (x *EnrollmentRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *EnrollmentRequest) GetNetworkName() string {
	if x != nil {
		return x.NetworkName
	}
	return ""
}

func (x *EnrollmentRequest) GetCsrPEM() string {
	if x != nil {
		return x.CsrPEM
	}
	return ""
}

func (x *EnrollmentRequest) GetClientIP() string {
	if x != nil {
		return x.ClientIP
	}
	return ""
}

func (x *EnrollmentRequest) GetGroups() []string {
	if x != nil {
		return x.Groups
	}
	return nil
}

func (x *EnrollmentRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EnrollmentRequest) GetRequestedIP() string {
	if x != nil {
		return x.RequestedIP
	}
	return ""
}

type Agent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fingerprint   []byte                 `protobuf:"bytes,1,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	Created       *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created,proto3" json:"created,omitempty"`
	NetworkName   string                 `protobuf:"bytes,3,opt,name=networkName,proto3" json:"networkName,omitempty"`
	Groups        []string               `protobuf:"bytes,4,rep,name=groups,proto3" json:"groups,omitempty"`
	CsrPEM        string                 `protobuf:"bytes,5,opt,name=csrPEM,proto3" json:"csrPEM,omitempty"`
	AssignedIP    string                 `protobuf:"bytes,6,opt,name=assignedIP,proto3" json:"assignedIP,omitempty"`
	SignedPEM     string                 `protobuf:"bytes,10,opt,name=signedPEM,proto3" json:"signedPEM,omitempty"`
	IssuedAt      *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=issuedAt,proto3" json:"issuedAt,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=expiresAt,proto3" json:"expiresAt,omitempty"`
	Name          string                 `protobuf:"bytes,13,opt,name=name,proto3" json:"name,omitempty"`
	OldSignedPEMs []string               `protobuf:"bytes,20,rep,name=oldSignedPEMs,proto3" json:"oldSignedPEMs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Agent) Reset() {
	*x = Agent{}
	mi := &file_server_store_store_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Agent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Agent) ProtoMessage() {}

func (x *Agent) ProtoReflect() protoreflect.Message {
	mi := &file_server_store_store_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Agent.ProtoReflect.Descriptor instead.
func (*Agent) Descriptor() ([]byte, []int) {
	return file_server_store_store_proto_rawDescGZIP(), []int{3}
}

func (x *Agent) GetFingerprint() []byte {
	if x != nil {
		return x.Fingerprint
	}
	return nil
}

func (x *Agent) GetCreated() *timestamppb.Timestamp {
	if x != nil {
		return x.Created
	}
	return nil
}

func (x *Agent) GetNetworkName() string {
	if x != nil {
		return x.NetworkName
	}
	return ""
}

func (x *Agent) GetGroups() []string {
	if x != nil {
		return x.Groups
	}
	return nil
}

func (x *Agent) GetCsrPEM() string {
	if x != nil {
		return x.CsrPEM
	}
	return ""
}

func (x *Agent) GetAssignedIP() string {
	if x != nil {
		return x.AssignedIP
	}
	return ""
}

func (x *Agent) GetSignedPEM() string {
	if x != nil {
		return x.SignedPEM
	}
	return ""
}

func (x *Agent) GetIssuedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.IssuedAt
	}
	return nil
}

func (x *Agent) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *Agent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Agent) GetOldSignedPEMs() []string {
	if x != nil {
		return x.OldSignedPEMs
	}
	return nil
}

type IPRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       []byte                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Netmask       []byte                 `protobuf:"bytes,2,opt,name=netmask,proto3" json:"netmask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IPRange) Reset() {
	*x = IPRange{}
	mi := &file_server_store_store_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IPRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IPRange) ProtoMessage() {}

func (x *IPRange) ProtoReflect() protoreflect.Message {
	mi := &file_server_store_store_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IPRange.ProtoReflect.Descriptor instead.
func (*IPRange) Descriptor() ([]byte, []int) {
	return file_server_store_store_proto_rawDescGZIP(), []int{4}
}

func (x *IPRange) GetNetwork() []byte {
	if x != nil {
		return x.Network
	}
	return nil
}

func (x *IPRange) GetNetmask() []byte {
	if x != nil {
		return x.Netmask
	}
	return nil
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Created       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created,proto3" json:"created,omitempty"`
	Approve       *UserApprove           `protobuf:"bytes,10,opt,name=approve,proto3" json:"approve,omitempty"`
	Disabled      bool                   `protobuf:"varint,11,opt,name=disabled,proto3" json:"disabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_server_store_store_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_server_store_store_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_server_store_store_proto_rawDescGZIP(), []int{5}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetCreated() *timestamppb.Timestamp {
	if x != nil {
		return x.Created
	}
	return nil
}

func (x *User) GetApprove() *UserApprove {
	if x != nil {
		return x.Approve
	}
	return nil
}

func (x *User) GetDisabled() bool {
	if x != nil {
		return x.Disabled
	}
	return false
}

type UserApprove struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Approved      bool                   `protobuf:"varint,1,opt,name=approved,proto3" json:"approved,omitempty"`
	ApprovedBy    string                 `protobuf:"bytes,2,opt,name=approvedBy,proto3" json:"approvedBy,omitempty"`
	ApprovedAt    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=approvedAt,proto3" json:"approvedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserApprove) Reset() {
	*x = UserApprove{}
	mi := &file_server_store_store_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserApprove) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserApprove) ProtoMessage() {}

func (x *UserApprove) ProtoReflect() protoreflect.Message {
	mi := &file_server_store_store_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserApprove.ProtoReflect.Descriptor instead.
func (*UserApprove) Descriptor() ([]byte, []int) {
	return file_server_store_store_proto_rawDescGZIP(), []int{6}
}

func (x *UserApprove) GetApproved() bool {
	if x != nil {
		return x.Approved
	}
	return false
}

func (x *UserApprove) GetApprovedBy() string {
	if x != nil {
		return x.ApprovedBy
	}
	return ""
}

func (x *UserApprove) GetApprovedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ApprovedAt
	}
	return nil
}

var File_server_store_store_proto protoreflect.FileDescriptor

const file_server_store_store_proto_rawDesc = "" +
	"\n" +
	"\x18server/store/store.proto\x12\x05store\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe7\x01\n" +
	"\x02CA\x12 \n" +
	"\vnetworkName\x18\x01 \x01(\tR\vnetworkName\x12\x1c\n" +
	"\tpublicKey\x18\n" +
	" \x01(\fR\tpublicKey\x12\x1e\n" +
	"\n" +
	"privateKey\x18\v \x01(\fR\n" +
	"privateKey\x12\x1c\n" +
	"\tsha256sum\x18\f \x01(\tR\tsha256sum\x12(\n" +
	"\x06status\x18\x14 \x01(\x0e2\x10.store.CA.StatusR\x06status\"9\n" +
	"\x06Status\x12\n" +
	"\n" +
	"\x06Active\x10\x00\x12\v\n" +
	"\aExpired\x10\x01\x12\f\n" +
	"\bInactive\x10\x02\x12\b\n" +
	"\x04Next\x10\x03\"I\n" +
	"\x0fEnrollmentToken\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12 \n" +
	"\vnetworkName\x18\x02 \x01(\tR\vnetworkName\"\xa5\x02\n" +
	"\x11EnrollmentRequest\x12 \n" +
	"\vfingerprint\x18\x01 \x01(\fR\vfingerprint\x124\n" +
	"\acreated\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\acreated\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\x12 \n" +
	"\vnetworkName\x18\x04 \x01(\tR\vnetworkName\x12\x16\n" +
	"\x06csrPEM\x18\x05 \x01(\tR\x06csrPEM\x12\x1a\n" +
	"\bclientIP\x18\x06 \x01(\tR\bclientIP\x12\x16\n" +
	"\x06groups\x18\a \x03(\tR\x06groups\x12\x12\n" +
	"\x04name\x18\b \x01(\tR\x04name\x12 \n" +
	"\vrequestedIP\x18\t \x01(\tR\vrequestedIP\"\x9b\x03\n" +
	"\x05Agent\x12 \n" +
	"\vfingerprint\x18\x01 \x01(\fR\vfingerprint\x124\n" +
	"\acreated\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\acreated\x12 \n" +
	"\vnetworkName\x18\x03 \x01(\tR\vnetworkName\x12\x16\n" +
	"\x06groups\x18\x04 \x03(\tR\x06groups\x12\x16\n" +
	"\x06csrPEM\x18\x05 \x01(\tR\x06csrPEM\x12\x1e\n" +
	"\n" +
	"assignedIP\x18\x06 \x01(\tR\n" +
	"assignedIP\x12\x1c\n" +
	"\tsignedPEM\x18\n" +
	" \x01(\tR\tsignedPEM\x126\n" +
	"\bissuedAt\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\bissuedAt\x128\n" +
	"\texpiresAt\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12\x12\n" +
	"\x04name\x18\r \x01(\tR\x04name\x12$\n" +
	"\roldSignedPEMs\x18\x14 \x03(\tR\roldSignedPEMs\"=\n" +
	"\aIPRange\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\fR\anetwork\x12\x18\n" +
	"\anetmask\x18\x02 \x01(\fR\anetmask\"\xc0\x01\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x124\n" +
	"\acreated\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\acreated\x12,\n" +
	"\aapprove\x18\n" +
	" \x01(\v2\x12.store.UserApproveR\aapprove\x12\x1a\n" +
	"\bdisabled\x18\v \x01(\bR\bdisabled\"\x85\x01\n" +
	"\vUserApprove\x12\x1a\n" +
	"\bapproved\x18\x01 \x01(\bR\bapproved\x12\x1e\n" +
	"\n" +
	"approvedBy\x18\x02 \x01(\tR\n" +
	"approvedBy\x12:\n" +
	"\n" +
	"approvedAt\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"approvedAtB|\n" +
	"\tcom.storeB\n" +
	"StoreProtoP\x01Z/github.com/cego/nebula-provisioner/server/store\xa2\x02\x03SXX\xaa\x02\x05Store\xca\x02\x05Store\xe2\x02\x11Store\\GPBMetadata\xea\x02\x05Storeb\x06proto3"

var (
	file_server_store_store_proto_rawDescOnce sync.Once
	file_server_store_store_proto_rawDescData []byte
)

func file_server_store_store_proto_rawDescGZIP() []byte {
	file_server_store_store_proto_rawDescOnce.Do(func() {
		file_server_store_store_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_server_store_store_proto_rawDesc), len(file_server_store_store_proto_rawDesc)))
	})
	return file_server_store_store_proto_rawDescData
}

var file_server_store_store_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_server_store_store_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_server_store_store_proto_goTypes = []any{
	(CA_Status)(0),                // 0: store.CA.Status
	(*CA)(nil),                    // 1: store.CA
	(*EnrollmentToken)(nil),       // 2: store.EnrollmentToken
	(*EnrollmentRequest)(nil),     // 3: store.EnrollmentRequest
	(*Agent)(nil),                 // 4: store.Agent
	(*IPRange)(nil),               // 5: store.IPRange
	(*User)(nil),                  // 6: store.User
	(*UserApprove)(nil),           // 7: store.UserApprove
	(*timestamppb.Timestamp)(nil), // 8: google.protobuf.Timestamp
}
var file_server_store_store_proto_depIdxs = []int32{
	0, // 0: store.CA.status:type_name -> store.CA.Status
	8, // 1: store.EnrollmentRequest.created:type_name -> google.protobuf.Timestamp
	8, // 2: store.Agent.created:type_name -> google.protobuf.Timestamp
	8, // 3: store.Agent.issuedAt:type_name -> google.protobuf.Timestamp
	8, // 4: store.Agent.expiresAt:type_name -> google.protobuf.Timestamp
	8, // 5: store.User.created:type_name -> google.protobuf.Timestamp
	7, // 6: store.User.approve:type_name -> store.UserApprove
	8, // 7: store.UserApprove.approvedAt:type_name -> google.protobuf.Timestamp
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_server_store_store_proto_init() }
func file_server_store_store_proto_init() {
	if File_server_store_store_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_server_store_store_proto_rawDesc), len(file_server_store_store_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_server_store_store_proto_goTypes,
		DependencyIndexes: file_server_store_store_proto_depIdxs,
		EnumInfos:         file_server_store_store_proto_enumTypes,
		MessageInfos:      file_server_store_store_proto_msgTypes,
	}.Build()
	File_server_store_store_proto = out.File
	file_server_store_store_proto_goTypes = nil
	file_server_store_store_proto_depIdxs = nil
}
