// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: protocol/agent-service.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnrollRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	CsrPEM        string                 `protobuf:"bytes,2,opt,name=csrPEM,proto3" json:"csrPEM,omitempty"`
	Groups        []string               `protobuf:"bytes,3,rep,name=groups,proto3" json:"groups,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	RequestedIP   string                 `protobuf:"bytes,5,opt,name=requestedIP,proto3" json:"requestedIP,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollRequest) Reset() {
	*x = EnrollRequest{}
	mi := &file_protocol_agent_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollRequest) ProtoMessage() {}

func (x *EnrollRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_agent_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollRequest.ProtoReflect.Descriptor instead.
func (*EnrollRequest) Descriptor() ([]byte, []int) {
	return file_protocol_agent_service_proto_rawDescGZIP(), []int{0}
}

func (x *EnrollRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *EnrollRequest) GetCsrPEM() string {
	if x != nil {
		return x.CsrPEM
	}
	return ""
}

func (x *EnrollRequest) GetGroups() []string {
	if x != nil {
		return x.Groups
	}
	return nil
}

func (x *EnrollRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EnrollRequest) GetRequestedIP() string {
	if x != nil {
		return x.RequestedIP
	}
	return ""
}

type EnrollResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollResponse) Reset() {
	*x = EnrollResponse{}
	mi := &file_protocol_agent_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollResponse) ProtoMessage() {}

func (x *EnrollResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_agent_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollResponse.ProtoReflect.Descriptor instead.
func (*EnrollResponse) Descriptor() ([]byte, []int) {
	return file_protocol_agent_service_proto_rawDescGZIP(), []int{1}
}

type GetEnrollStatusResponse struct {
	state                     protoimpl.MessageState  `protogen:"open.v1"`
	IsEnrolled                bool                    `protobuf:"varint,1,opt,name=isEnrolled,proto3" json:"isEnrolled,omitempty"`
	IsEnrollmentRequested     bool                    `protobuf:"varint,2,opt,name=isEnrollmentRequested,proto3" json:"isEnrollmentRequested,omitempty"`
	EnrollmentRequest         *EnrollRequest          `protobuf:"bytes,3,opt,name=enrollmentRequest,proto3" json:"enrollmentRequest,omitempty"`
	SignedPEM                 string                  `protobuf:"bytes,10,opt,name=signedPEM,proto3" json:"signedPEM,omitempty"`
	IssuedAt                  *timestamppb.Timestamp  `protobuf:"bytes,11,opt,name=issuedAt,proto3" json:"issuedAt,omitempty"`
	ExpiresAt                 *timestamppb.Timestamp  `protobuf:"bytes,12,opt,name=expiresAt,proto3" json:"expiresAt,omitempty"`
	AssignedIP                string                  `protobuf:"bytes,13,opt,name=assignedIP,proto3" json:"assignedIP,omitempty"`
	Name                      string                  `protobuf:"bytes,14,opt,name=name,proto3" json:"name,omitempty"`
	Groups                    []string                `protobuf:"bytes,15,rep,name=groups,proto3" json:"groups,omitempty"`
	SignedPEMFingerprint      string                  `protobuf:"bytes,16,opt,name=signedPEMFingerprint,proto3" json:"signedPEMFingerprint,omitempty"`
	CertificateAuthorities    []*CertificateAuthority `protobuf:"bytes,20,rep,name=certificateAuthorities,proto3" json:"certificateAuthorities,omitempty"`
	CertificateRevocationList []*NetworkCRL           `protobuf:"bytes,21,rep,name=certificateRevocationList,proto3" json:"certificateRevocationList,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *GetEnrollStatusResponse) Reset() {
	*x = GetEnrollStatusResponse{}
	mi := &file_protocol_agent_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEnrollStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEnrollStatusResponse) ProtoMessage() {}

func (x *GetEnrollStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_agent_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEnrollStatusResponse.ProtoReflect.Descriptor instead.
func (*GetEnrollStatusResponse) Descriptor() ([]byte, []int) {
	return file_protocol_agent_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetEnrollStatusResponse) GetIsEnrolled() bool {
	if x != nil {
		return x.IsEnrolled
	}
	return false
}

func (x *GetEnrollStatusResponse) GetIsEnrollmentRequested() bool {
	if x != nil {
		return x.IsEnrollmentRequested
	}
	return false
}

func (x *GetEnrollStatusResponse) GetEnrollmentRequest() *EnrollRequest {
	if x != nil {
		return x.EnrollmentRequest
	}
	return nil
}

func (x *GetEnrollStatusResponse) GetSignedPEM() string {
	if x != nil {
		return x.SignedPEM
	}
	return ""
}

func (x *GetEnrollStatusResponse) GetIssuedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.IssuedAt
	}
	return nil
}

func (x *GetEnrollStatusResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *GetEnrollStatusResponse) GetAssignedIP() string {
	if x != nil {
		return x.AssignedIP
	}
	return ""
}

func (x *GetEnrollStatusResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetEnrollStatusResponse) GetGroups() []string {
	if x != nil {
		return x.Groups
	}
	return nil
}

func (x *GetEnrollStatusResponse) GetSignedPEMFingerprint() string {
	if x != nil {
		return x.SignedPEMFingerprint
	}
	return ""
}

func (x *GetEnrollStatusResponse) GetCertificateAuthorities() []*CertificateAuthority {
	if x != nil {
		return x.CertificateAuthorities
	}
	return nil
}

func (x *GetEnrollStatusResponse) GetCertificateRevocationList() []*NetworkCRL {
	if x != nil {
		return x.CertificateRevocationList
	}
	return nil
}

type GetCertificateAuthorityByNetworkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NetworkNames  []string               `protobuf:"bytes,1,rep,name=networkNames,proto3" json:"networkNames,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCertificateAuthorityByNetworkRequest) Reset() {
	*x = GetCertificateAuthorityByNetworkRequest{}
	mi := &file_protocol_agent_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCertificateAuthorityByNetworkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCertificateAuthorityByNetworkRequest) ProtoMessage() {}

func (x *GetCertificateAuthorityByNetworkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_agent_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCertificateAuthorityByNetworkRequest.ProtoReflect.Descriptor instead.
func (*GetCertificateAuthorityByNetworkRequest) Descriptor() ([]byte, []int) {
	return file_protocol_agent_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetCertificateAuthorityByNetworkRequest) GetNetworkNames() []string {
	if x != nil {
		return x.NetworkNames
	}
	return nil
}

type GetCertificateAuthorityByNetworkResponse struct {
	state                  protoimpl.MessageState  `protogen:"open.v1"`
	CertificateAuthorities []*CertificateAuthority `protobuf:"bytes,1,rep,name=certificateAuthorities,proto3" json:"certificateAuthorities,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GetCertificateAuthorityByNetworkResponse) Reset() {
	*x = GetCertificateAuthorityByNetworkResponse{}
	mi := &file_protocol_agent_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCertificateAuthorityByNetworkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCertificateAuthorityByNetworkResponse) ProtoMessage() {}

func (x *GetCertificateAuthorityByNetworkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_agent_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCertificateAuthorityByNetworkResponse.ProtoReflect.Descriptor instead.
func (*GetCertificateAuthorityByNetworkResponse) Descriptor() ([]byte, []int) {
	return file_protocol_agent_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetCertificateAuthorityByNetworkResponse) GetCertificateAuthorities() []*CertificateAuthority {
	if x != nil {
		return x.CertificateAuthorities
	}
	return nil
}

type GetCRLByNetworkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NetworkNames  []string               `protobuf:"bytes,1,rep,name=networkNames,proto3" json:"networkNames,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCRLByNetworkRequest) Reset() {
	*x = GetCRLByNetworkRequest{}
	mi := &file_protocol_agent_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCRLByNetworkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCRLByNetworkRequest) ProtoMessage() {}

func (x *GetCRLByNetworkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_agent_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCRLByNetworkRequest.ProtoReflect.Descriptor instead.
func (*GetCRLByNetworkRequest) Descriptor() ([]byte, []int) {
	return file_protocol_agent_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetCRLByNetworkRequest) GetNetworkNames() []string {
	if x != nil {
		return x.NetworkNames
	}
	return nil
}

type GetCRLByNetworkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Crls          []*NetworkCRL          `protobuf:"bytes,1,rep,name=crls,proto3" json:"crls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCRLByNetworkResponse) Reset() {
	*x = GetCRLByNetworkResponse{}
	mi := &file_protocol_agent_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCRLByNetworkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCRLByNetworkResponse) ProtoMessage() {}

func (x *GetCRLByNetworkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_agent_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCRLByNetworkResponse.ProtoReflect.Descriptor instead.
func (*GetCRLByNetworkResponse) Descriptor() ([]byte, []int) {
	return file_protocol_agent_service_proto_rawDescGZIP(), []int{6}
}

func (x *GetCRLByNetworkResponse) GetCrls() []*NetworkCRL {
	if x != nil {
		return x.Crls
	}
	return nil
}

var File_protocol_agent_service_proto protoreflect.FileDescriptor

const file_protocol_agent_service_proto_rawDesc = "" +
	"\n" +
	"\x1cprotocol/agent-service.proto\x12\bprotocol\x1a\x15protocol/models.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8b\x01\n" +
	"\rEnrollRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x16\n" +
	"\x06csrPEM\x18\x02 \x01(\tR\x06csrPEM\x12\x16\n" +
	"\x06groups\x18\x03 \x03(\tR\x06groups\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12 \n" +
	"\vrequestedIP\x18\x05 \x01(\tR\vrequestedIP\"\x10\n" +
	"\x0eEnrollResponse\"\xf2\x04\n" +
	"\x17GetEnrollStatusResponse\x12\x1e\n" +
	"\n" +
	"isEnrolled\x18\x01 \x01(\bR\n" +
	"isEnrolled\x124\n" +
	"\x15isEnrollmentRequested\x18\x02 \x01(\bR\x15isEnrollmentRequested\x12E\n" +
	"\x11enrollmentRequest\x18\x03 \x01(\v2\x17.protocol.EnrollRequestR\x11enrollmentRequest\x12\x1c\n" +
	"\tsignedPEM\x18\n" +
	" \x01(\tR\tsignedPEM\x126\n" +
	"\bissuedAt\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\bissuedAt\x128\n" +
	"\texpiresAt\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12\x1e\n" +
	"\n" +
	"assignedIP\x18\r \x01(\tR\n" +
	"assignedIP\x12\x12\n" +
	"\x04name\x18\x0e \x01(\tR\x04name\x12\x16\n" +
	"\x06groups\x18\x0f \x03(\tR\x06groups\x122\n" +
	"\x14signedPEMFingerprint\x18\x10 \x01(\tR\x14signedPEMFingerprint\x12V\n" +
	"\x16certificateAuthorities\x18\x14 \x03(\v2\x1e.protocol.CertificateAuthorityR\x16certificateAuthorities\x12R\n" +
	"\x19certificateRevocationList\x18\x15 \x03(\v2\x14.protocol.NetworkCRLR\x19certificateRevocationList\"M\n" +
	"'GetCertificateAuthorityByNetworkRequest\x12\"\n" +
	"\fnetworkNames\x18\x01 \x03(\tR\fnetworkNames\"\x82\x01\n" +
	"(GetCertificateAuthorityByNetworkResponse\x12V\n" +
	"\x16certificateAuthorities\x18\x01 \x03(\v2\x1e.protocol.CertificateAuthorityR\x16certificateAuthorities\"<\n" +
	"\x16GetCRLByNetworkRequest\x12\"\n" +
	"\fnetworkNames\x18\x01 \x03(\tR\fnetworkNames\"C\n" +
	"\x17GetCRLByNetworkResponse\x12(\n" +
	"\x04crls\x18\x01 \x03(\v2\x14.protocol.NetworkCRLR\x04crls2\x85\x03\n" +
	"\fAgentService\x12=\n" +
	"\x06Enroll\x12\x17.protocol.EnrollRequest\x1a\x18.protocol.EnrollResponse\"\x00\x12N\n" +
	"\x0fGetEnrollStatus\x12\x16.google.protobuf.Empty\x1a!.protocol.GetEnrollStatusResponse\"\x00\x12\x8b\x01\n" +
	" GetCertificateAuthorityByNetwork\x121.protocol.GetCertificateAuthorityByNetworkRequest\x1a2.protocol.GetCertificateAuthorityByNetworkResponse\"\x00\x12X\n" +
	"\x0fGetCRLByNetwork\x12 .protocol.GetCRLByNetworkRequest\x1a!.protocol.GetCRLByNetworkResponse\"\x00B\x8e\x01\n" +
	"\fcom.protocolB\x11AgentServiceProtoP\x01Z+github.com/cego/nebula-provisioner/protocol\xa2\x02\x03PXX\xaa\x02\bProtocol\xca\x02\bProtocol\xe2\x02\x14Protocol\\GPBMetadata\xea\x02\bProtocolb\x06proto3"

var (
	file_protocol_agent_service_proto_rawDescOnce sync.Once
	file_protocol_agent_service_proto_rawDescData []byte
)

func file_protocol_agent_service_proto_rawDescGZIP() []byte {
	file_protocol_agent_service_proto_rawDescOnce.Do(func() {
		file_protocol_agent_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protocol_agent_service_proto_rawDesc), len(file_protocol_agent_service_proto_rawDesc)))
	})
	return file_protocol_agent_service_proto_rawDescData
}

var file_protocol_agent_service_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_protocol_agent_service_proto_goTypes = []any{
	(*EnrollRequest)(nil),                            // 0: protocol.EnrollRequest
	(*EnrollResponse)(nil),                           // 1: protocol.EnrollResponse
	(*GetEnrollStatusResponse)(nil),                  // 2: protocol.GetEnrollStatusResponse
	(*GetCertificateAuthorityByNetworkRequest)(nil),  // 3: protocol.GetCertificateAuthorityByNetworkRequest
	(*GetCertificateAuthorityByNetworkResponse)(nil), // 4: protocol.GetCertificateAuthorityByNetworkResponse
	(*GetCRLByNetworkRequest)(nil),                   // 5: protocol.GetCRLByNetworkRequest
	(*GetCRLByNetworkResponse)(nil),                  // 6: protocol.GetCRLByNetworkResponse
	(*timestamppb.Timestamp)(nil),                    // 7: google.protobuf.Timestamp
	(*CertificateAuthority)(nil),                     // 8: protocol.CertificateAuthority
	(*NetworkCRL)(nil),                               // 9: protocol.NetworkCRL
	(*emptypb.Empty)(nil),                            // 10: google.protobuf.Empty
}
var file_protocol_agent_service_proto_depIdxs = []int32{
	0,  // 0: protocol.GetEnrollStatusResponse.enrollmentRequest:type_name -> protocol.EnrollRequest
	7,  // 1: protocol.GetEnrollStatusResponse.issuedAt:type_name -> google.protobuf.Timestamp
	7,  // 2: protocol.GetEnrollStatusResponse.expiresAt:type_name -> google.protobuf.Timestamp
	8,  // 3: protocol.GetEnrollStatusResponse.certificateAuthorities:type_name -> protocol.CertificateAuthority
	9,  // 4: protocol.GetEnrollStatusResponse.certificateRevocationList:type_name -> protocol.NetworkCRL
	8,  // 5: protocol.GetCertificateAuthorityByNetworkResponse.certificateAuthorities:type_name -> protocol.CertificateAuthority
	9,  // 6: protocol.GetCRLByNetworkResponse.crls:type_name -> protocol.NetworkCRL
	0,  // 7: protocol.AgentService.Enroll:input_type -> protocol.EnrollRequest
	10, // 8: protocol.AgentService.GetEnrollStatus:input_type -> google.protobuf.Empty
	3,  // 9: protocol.AgentService.GetCertificateAuthorityByNetwork:input_type -> protocol.GetCertificateAuthorityByNetworkRequest
	5,  // 10: protocol.AgentService.GetCRLByNetwork:input_type -> protocol.GetCRLByNetworkRequest
	1,  // 11: protocol.AgentService.Enroll:output_type -> protocol.EnrollResponse
	2,  // 12: protocol.AgentService.GetEnrollStatus:output_type -> protocol.GetEnrollStatusResponse
	4,  // 13: protocol.AgentService.GetCertificateAuthorityByNetwork:output_type -> protocol.GetCertificateAuthorityByNetworkResponse
	6,  // 14: protocol.AgentService.GetCRLByNetwork:output_type -> protocol.GetCRLByNetworkResponse
	11, // [11:15] is the sub-list for method output_type
	7,  // [7:11] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_protocol_agent_service_proto_init() }
func file_protocol_agent_service_proto_init() {
	if File_protocol_agent_service_proto != nil {
		return
	}
	file_protocol_models_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protocol_agent_service_proto_rawDesc), len(file_protocol_agent_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protocol_agent_service_proto_goTypes,
		DependencyIndexes: file_protocol_agent_service_proto_depIdxs,
		MessageInfos:      file_protocol_agent_service_proto_msgTypes,
	}.Build()
	File_protocol_agent_service_proto = out.File
	file_protocol_agent_service_proto_goTypes = nil
	file_protocol_agent_service_proto_depIdxs = nil
}
