// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: protocol/models.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CertificateAuthority struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NetworkName   string                 `protobuf:"bytes,1,opt,name=networkName,proto3" json:"networkName,omitempty"`
	PublicKeyPEM  string                 `protobuf:"bytes,10,opt,name=publicKeyPEM,proto3" json:"publicKeyPEM,omitempty"`
	Sha256Sum     string                 `protobuf:"bytes,11,opt,name=sha256sum,proto3" json:"sha256sum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CertificateAuthority) Reset() {
	*x = CertificateAuthority{}
	mi := &file_protocol_models_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CertificateAuthority) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CertificateAuthority) ProtoMessage() {}

func (x *CertificateAuthority) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_models_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CertificateAuthority.ProtoReflect.Descriptor instead.
func (*CertificateAuthority) Descriptor() ([]byte, []int) {
	return file_protocol_models_proto_rawDescGZIP(), []int{0}
}

func (x *CertificateAuthority) GetNetworkName() string {
	if x != nil {
		return x.NetworkName
	}
	return ""
}

func (x *CertificateAuthority) GetPublicKeyPEM() string {
	if x != nil {
		return x.PublicKeyPEM
	}
	return ""
}

func (x *CertificateAuthority) GetSha256Sum() string {
	if x != nil {
		return x.Sha256Sum
	}
	return ""
}

type NetworkCRL struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NetworkName   string                 `protobuf:"bytes,1,opt,name=networkName,proto3" json:"networkName,omitempty"`
	Fingerprints  []string               `protobuf:"bytes,2,rep,name=fingerprints,proto3" json:"fingerprints,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkCRL) Reset() {
	*x = NetworkCRL{}
	mi := &file_protocol_models_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkCRL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkCRL) ProtoMessage() {}

func (x *NetworkCRL) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_models_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkCRL.ProtoReflect.Descriptor instead.
func (*NetworkCRL) Descriptor() ([]byte, []int) {
	return file_protocol_models_proto_rawDescGZIP(), []int{1}
}

func (x *NetworkCRL) GetNetworkName() string {
	if x != nil {
		return x.NetworkName
	}
	return ""
}

func (x *NetworkCRL) GetFingerprints() []string {
	if x != nil {
		return x.Fingerprints
	}
	return nil
}

var File_protocol_models_proto protoreflect.FileDescriptor

const file_protocol_models_proto_rawDesc = "" +
	"\n" +
	"\x15protocol/models.proto\x12\bprotocol\"z\n" +
	"\x14CertificateAuthority\x12 \n" +
	"\vnetworkName\x18\x01 \x01(\tR\vnetworkName\x12\"\n" +
	"\fpublicKeyPEM\x18\n" +
	" \x01(\tR\fpublicKeyPEM\x12\x1c\n" +
	"\tsha256sum\x18\v \x01(\tR\tsha256sum\"R\n" +
	"\n" +
	"NetworkCRL\x12 \n" +
	"\vnetworkName\x18\x01 \x01(\tR\vnetworkName\x12\"\n" +
	"\ffingerprints\x18\x02 \x03(\tR\ffingerprintsB\x88\x01\n" +
	"\fcom.protocolB\vModelsProtoP\x01Z+github.com/cego/nebula-provisioner/protocol\xa2\x02\x03PXX\xaa\x02\bProtocol\xca\x02\bProtocol\xe2\x02\x14Protocol\\GPBMetadata\xea\x02\bProtocolb\x06proto3"

var (
	file_protocol_models_proto_rawDescOnce sync.Once
	file_protocol_models_proto_rawDescData []byte
)

func file_protocol_models_proto_rawDescGZIP() []byte {
	file_protocol_models_proto_rawDescOnce.Do(func() {
		file_protocol_models_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protocol_models_proto_rawDesc), len(file_protocol_models_proto_rawDesc)))
	})
	return file_protocol_models_proto_rawDescData
}

var file_protocol_models_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protocol_models_proto_goTypes = []any{
	(*CertificateAuthority)(nil), // 0: protocol.CertificateAuthority
	(*NetworkCRL)(nil),           // 1: protocol.NetworkCRL
}
var file_protocol_models_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protocol_models_proto_init() }
func file_protocol_models_proto_init() {
	if File_protocol_models_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protocol_models_proto_rawDesc), len(file_protocol_models_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protocol_models_proto_goTypes,
		DependencyIndexes: file_protocol_models_proto_depIdxs,
		MessageInfos:      file_protocol_models_proto_msgTypes,
	}.Build()
	File_protocol_models_proto = out.File
	file_protocol_models_proto_goTypes = nil
	file_protocol_models_proto_depIdxs = nil
}
