// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: protocol/server-command.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyParts      uint32                 `protobuf:"varint,1,opt,name=keyParts,proto3" json:"keyParts,omitempty"`
	KeyThreshold  uint32                 `protobuf:"varint,2,opt,name=keyThreshold,proto3" json:"keyThreshold,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitRequest) Reset() {
	*x = InitRequest{}
	mi := &file_protocol_server_command_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitRequest) ProtoMessage() {}

func (x *InitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_server_command_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitRequest.ProtoReflect.Descriptor instead.
func (*InitRequest) Descriptor() ([]byte, []int) {
	return file_protocol_server_command_proto_rawDescGZIP(), []int{0}
}

func (x *InitRequest) GetKeyParts() uint32 {
	if x != nil {
		return x.KeyParts
	}
	return 0
}

func (x *InitRequest) GetKeyThreshold() uint32 {
	if x != nil {
		return x.KeyThreshold
	}
	return 0
}

type InitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyParts      []string               `protobuf:"bytes,1,rep,name=keyParts,proto3" json:"keyParts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitResponse) Reset() {
	*x = InitResponse{}
	mi := &file_protocol_server_command_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitResponse) ProtoMessage() {}

func (x *InitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_server_command_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitResponse.ProtoReflect.Descriptor instead.
func (*InitResponse) Descriptor() ([]byte, []int) {
	return file_protocol_server_command_proto_rawDescGZIP(), []int{1}
}

func (x *InitResponse) GetKeyParts() []string {
	if x != nil {
		return x.KeyParts
	}
	return nil
}

type IsInitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsInitialized bool                   `protobuf:"varint,1,opt,name=isInitialized,proto3" json:"isInitialized,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsInitResponse) Reset() {
	*x = IsInitResponse{}
	mi := &file_protocol_server_command_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsInitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsInitResponse) ProtoMessage() {}

func (x *IsInitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_server_command_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsInitResponse.ProtoReflect.Descriptor instead.
func (*IsInitResponse) Descriptor() ([]byte, []int) {
	return file_protocol_server_command_proto_rawDescGZIP(), []int{2}
}

func (x *IsInitResponse) GetIsInitialized() bool {
	if x != nil {
		return x.IsInitialized
	}
	return false
}

type UnsealRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	KeyPart             string                 `protobuf:"bytes,1,opt,name=keyPart,proto3" json:"keyPart,omitempty"`
	RemoveExistingParts bool                   `protobuf:"varint,2,opt,name=removeExistingParts,proto3" json:"removeExistingParts,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *UnsealRequest) Reset() {
	*x = UnsealRequest{}
	mi := &file_protocol_server_command_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnsealRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnsealRequest) ProtoMessage() {}

func (x *UnsealRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_server_command_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnsealRequest.ProtoReflect.Descriptor instead.
func (*UnsealRequest) Descriptor() ([]byte, []int) {
	return file_protocol_server_command_proto_rawDescGZIP(), []int{3}
}

func (x *UnsealRequest) GetKeyPart() string {
	if x != nil {
		return x.KeyPart
	}
	return ""
}

func (x *UnsealRequest) GetRemoveExistingParts() bool {
	if x != nil {
		return x.RemoveExistingParts
	}
	return false
}

type UnsealResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnsealResponse) Reset() {
	*x = UnsealResponse{}
	mi := &file_protocol_server_command_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnsealResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnsealResponse) ProtoMessage() {}

func (x *UnsealResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_server_command_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnsealResponse.ProtoReflect.Descriptor instead.
func (*UnsealResponse) Descriptor() ([]byte, []int) {
	return file_protocol_server_command_proto_rawDescGZIP(), []int{4}
}

type CreateNetworkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Duration      *durationpb.Duration   `protobuf:"bytes,2,opt,name=duration,proto3" json:"duration,omitempty"`
	Groups        []string               `protobuf:"bytes,3,rep,name=groups,proto3" json:"groups,omitempty"`
	Ips           []string               `protobuf:"bytes,4,rep,name=ips,proto3" json:"ips,omitempty"`
	Subnets       []string               `protobuf:"bytes,5,rep,name=subnets,proto3" json:"subnets,omitempty"`
	IpPools       []string               `protobuf:"bytes,6,rep,name=ipPools,proto3" json:"ipPools,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNetworkRequest) Reset() {
	*x = CreateNetworkRequest{}
	mi := &file_protocol_server_command_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNetworkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNetworkRequest) ProtoMessage() {}

func (x *CreateNetworkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_server_command_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNetworkRequest.ProtoReflect.Descriptor instead.
func (*CreateNetworkRequest) Descriptor() ([]byte, []int) {
	return file_protocol_server_command_proto_rawDescGZIP(), []int{5}
}

func (x *CreateNetworkRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateNetworkRequest) GetDuration() *durationpb.Duration {
	if x != nil {
		return x.Duration
	}
	return nil
}

func (x *CreateNetworkRequest) GetGroups() []string {
	if x != nil {
		return x.Groups
	}
	return nil
}

func (x *CreateNetworkRequest) GetIps() []string {
	if x != nil {
		return x.Ips
	}
	return nil
}

func (x *CreateNetworkRequest) GetSubnets() []string {
	if x != nil {
		return x.Subnets
	}
	return nil
}

func (x *CreateNetworkRequest) GetIpPools() []string {
	if x != nil {
		return x.IpPools
	}
	return nil
}

type CreateNetworkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       *Network               `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNetworkResponse) Reset() {
	*x = CreateNetworkResponse{}
	mi := &file_protocol_server_command_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNetworkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNetworkResponse) ProtoMessage() {}

func (x *CreateNetworkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_server_command_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNetworkResponse.ProtoReflect.Descriptor instead.
func (*CreateNetworkResponse) Descriptor() ([]byte, []int) {
	return file_protocol_server_command_proto_rawDescGZIP(), []int{6}
}

func (x *CreateNetworkResponse) GetNetwork() *Network {
	if x != nil {
		return x.Network
	}
	return nil
}

type ListNetworkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNetworkRequest) Reset() {
	*x = ListNetworkRequest{}
	mi := &file_protocol_server_command_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNetworkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNetworkRequest) ProtoMessage() {}

func (x *ListNetworkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_server_command_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNetworkRequest.ProtoReflect.Descriptor instead.
func (*ListNetworkRequest) Descriptor() ([]byte, []int) {
	return file_protocol_server_command_proto_rawDescGZIP(), []int{7}
}

type ListNetworkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Networks      []*Network             `protobuf:"bytes,1,rep,name=networks,proto3" json:"networks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNetworkResponse) Reset() {
	*x = ListNetworkResponse{}
	mi := &file_protocol_server_command_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNetworkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNetworkResponse) ProtoMessage() {}

func (x *ListNetworkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_server_command_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNetworkResponse.ProtoReflect.Descriptor instead.
func (*ListNetworkResponse) Descriptor() ([]byte, []int) {
	return file_protocol_server_command_proto_rawDescGZIP(), []int{8}
}

func (x *ListNetworkResponse) GetNetworks() []*Network {
	if x != nil {
		return x.Networks
	}
	return nil
}

type Network struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Duration      *durationpb.Duration   `protobuf:"bytes,2,opt,name=duration,proto3" json:"duration,omitempty"`
	Groups        []string               `protobuf:"bytes,3,rep,name=groups,proto3" json:"groups,omitempty"`
	Ips           []string               `protobuf:"bytes,4,rep,name=ips,proto3" json:"ips,omitempty"`
	Subnets       []string               `protobuf:"bytes,5,rep,name=subnets,proto3" json:"subnets,omitempty"`
	IpPools       []string               `protobuf:"bytes,6,rep,name=ipPools,proto3" json:"ipPools,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Network) Reset() {
	*x = Network{}
	mi := &file_protocol_server_command_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Network) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Network) ProtoMessage() {}

func (x *Network) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_server_command_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Network.ProtoReflect.Descriptor instead.
func (*Network) Descriptor() ([]byte, []int) {
	return file_protocol_server_command_proto_rawDescGZIP(), []int{9}
}

func (x *Network) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Network) GetDuration() *durationpb.Duration {
	if x != nil {
		return x.Duration
	}
	return nil
}

func (x *Network) GetGroups() []string {
	if x != nil {
		return x.Groups
	}
	return nil
}

func (x *Network) GetIps() []string {
	if x != nil {
		return x.Ips
	}
	return nil
}

func (x *Network) GetSubnets() []string {
	if x != nil {
		return x.Subnets
	}
	return nil
}

func (x *Network) GetIpPools() []string {
	if x != nil {
		return x.IpPools
	}
	return nil
}

type ListCertificateAuthorityByNetworkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NetworkNames  []string               `protobuf:"bytes,1,rep,name=networkNames,proto3" json:"networkNames,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCertificateAuthorityByNetworkRequest) Reset() {
	*x = ListCertificateAuthorityByNetworkRequest{}
	mi := &file_protocol_server_command_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCertificateAuthorityByNetworkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCertificateAuthorityByNetworkRequest) ProtoMessage() {}

func (x *ListCertificateAuthorityByNetworkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_server_command_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCertificateAuthorityByNetworkRequest.ProtoReflect.Descriptor instead.
func (*ListCertificateAuthorityByNetworkRequest) Descriptor() ([]byte, []int) {
	return file_protocol_server_command_proto_rawDescGZIP(), []int{10}
}

func (x *ListCertificateAuthorityByNetworkRequest) GetNetworkNames() []string {
	if x != nil {
		return x.NetworkNames
	}
	return nil
}

type ListCertificateAuthorityByNetworkResponse struct {
	state                  protoimpl.MessageState  `protogen:"open.v1"`
	CertificateAuthorities []*CertificateAuthority `protobuf:"bytes,1,rep,name=certificateAuthorities,proto3" json:"certificateAuthorities,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ListCertificateAuthorityByNetworkResponse) Reset() {
	*x = ListCertificateAuthorityByNetworkResponse{}
	mi := &file_protocol_server_command_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCertificateAuthorityByNetworkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCertificateAuthorityByNetworkResponse) ProtoMessage() {}

func (x *ListCertificateAuthorityByNetworkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_server_command_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCertificateAuthorityByNetworkResponse.ProtoReflect.Descriptor instead.
func (*ListCertificateAuthorityByNetworkResponse) Descriptor() ([]byte, []int) {
	return file_protocol_server_command_proto_rawDescGZIP(), []int{11}
}

func (x *ListCertificateAuthorityByNetworkResponse) GetCertificateAuthorities() []*CertificateAuthority {
	if x != nil {
		return x.CertificateAuthorities
	}
	return nil
}

type GetEnrollmentTokenForNetworkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEnrollmentTokenForNetworkRequest) Reset() {
	*x = GetEnrollmentTokenForNetworkRequest{}
	mi := &file_protocol_server_command_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEnrollmentTokenForNetworkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEnrollmentTokenForNetworkRequest) ProtoMessage() {}

func (x *GetEnrollmentTokenForNetworkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_server_command_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEnrollmentTokenForNetworkRequest.ProtoReflect.Descriptor instead.
func (*GetEnrollmentTokenForNetworkRequest) Descriptor() ([]byte, []int) {
	return file_protocol_server_command_proto_rawDescGZIP(), []int{12}
}

func (x *GetEnrollmentTokenForNetworkRequest) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

type GetEnrollmentTokenForNetworkResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	EnrollmentToken string                 `protobuf:"bytes,1,opt,name=enrollmentToken,proto3" json:"enrollmentToken,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetEnrollmentTokenForNetworkResponse) Reset() {
	*x = GetEnrollmentTokenForNetworkResponse{}
	mi := &file_protocol_server_command_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEnrollmentTokenForNetworkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEnrollmentTokenForNetworkResponse) ProtoMessage() {}

func (x *GetEnrollmentTokenForNetworkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_server_command_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEnrollmentTokenForNetworkResponse.ProtoReflect.Descriptor instead.
func (*GetEnrollmentTokenForNetworkResponse) Descriptor() ([]byte, []int) {
	return file_protocol_server_command_proto_rawDescGZIP(), []int{13}
}

func (x *GetEnrollmentTokenForNetworkResponse) GetEnrollmentToken() string {
	if x != nil {
		return x.EnrollmentToken
	}
	return ""
}

type ListEnrollmentRequestsResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	EnrollmentRequests []*EnrollmentRequest   `protobuf:"bytes,1,rep,name=enrollmentRequests,proto3" json:"enrollmentRequests,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ListEnrollmentRequestsResponse) Reset() {
	*x = ListEnrollmentRequestsResponse{}
	mi := &file_protocol_server_command_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEnrollmentRequestsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEnrollmentRequestsResponse) ProtoMessage() {}

func (x *ListEnrollmentRequestsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_server_command_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEnrollmentRequestsResponse.ProtoReflect.Descriptor instead.
func (*ListEnrollmentRequestsResponse) Descriptor() ([]byte, []int) {
	return file_protocol_server_command_proto_rawDescGZIP(), []int{14}
}

func (x *ListEnrollmentRequestsResponse) GetEnrollmentRequests() []*EnrollmentRequest {
	if x != nil {
		return x.EnrollmentRequests
	}
	return nil
}

type EnrollmentRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ClientFingerprint string                 `protobuf:"bytes,1,opt,name=clientFingerprint,proto3" json:"clientFingerprint,omitempty"`
	Created           *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created,proto3" json:"created,omitempty"`
	NetworkName       string                 `protobuf:"bytes,3,opt,name=networkName,proto3" json:"networkName,omitempty"`
	ClientIP          string                 `protobuf:"bytes,4,opt,name=clientIP,proto3" json:"clientIP,omitempty"`
	Name              string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *EnrollmentRequest) Reset() {
	*x = EnrollmentRequest{}
	mi := &file_protocol_server_command_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollmentRequest) ProtoMessage() {}

func (x *EnrollmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_server_command_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollmentRequest.ProtoReflect.Descriptor instead.
func (*EnrollmentRequest) Descriptor() ([]byte, []int) {
	return file_protocol_server_command_proto_rawDescGZIP(), []int{15}
}

func (x *EnrollmentRequest) GetClientFingerprint() string {
	if x != nil {
		return x.ClientFingerprint
	}
	return ""
}

func (x *EnrollmentRequest) GetCreated() *timestamppb.Timestamp {
	if x != nil {
		return x.Created
	}
	return nil
}

func (x *EnrollmentRequest) GetNetworkName() string {
	if x != nil {
		return x.NetworkName
	}
	return ""
}

func (x *EnrollmentRequest) GetClientIP() string {
	if x != nil {
		return x.ClientIP
	}
	return ""
}

func (x *EnrollmentRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ApproveEnrollmentRequestRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ClientFingerprint string                 `protobuf:"bytes,1,opt,name=clientFingerprint,proto3" json:"clientFingerprint,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ApproveEnrollmentRequestRequest) Reset() {
	*x = ApproveEnrollmentRequestRequest{}
	mi := &file_protocol_server_command_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveEnrollmentRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveEnrollmentRequestRequest) ProtoMessage() {}

func (x *ApproveEnrollmentRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_server_command_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveEnrollmentRequestRequest.ProtoReflect.Descriptor instead.
func (*ApproveEnrollmentRequestRequest) Descriptor() ([]byte, []int) {
	return file_protocol_server_command_proto_rawDescGZIP(), []int{16}
}

func (x *ApproveEnrollmentRequestRequest) GetClientFingerprint() string {
	if x != nil {
		return x.ClientFingerprint
	}
	return ""
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Created       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created,proto3" json:"created,omitempty"`
	Approve       *UserApprove           `protobuf:"bytes,10,opt,name=approve,proto3" json:"approve,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_protocol_server_command_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_server_command_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_protocol_server_command_proto_rawDescGZIP(), []int{17}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetCreated() *timestamppb.Timestamp {
	if x != nil {
		return x.Created
	}
	return nil
}

func (x *User) GetApprove() *UserApprove {
	if x != nil {
		return x.Approve
	}
	return nil
}

type UserApprove struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Approved      bool                   `protobuf:"varint,1,opt,name=approved,proto3" json:"approved,omitempty"`
	ApprovedBy    string                 `protobuf:"bytes,2,opt,name=approvedBy,proto3" json:"approvedBy,omitempty"`
	ApprovedAt    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=approvedAt,proto3" json:"approvedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserApprove) Reset() {
	*x = UserApprove{}
	mi := &file_protocol_server_command_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserApprove) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserApprove) ProtoMessage() {}

func (x *UserApprove) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_server_command_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserApprove.ProtoReflect.Descriptor instead.
func (*UserApprove) Descriptor() ([]byte, []int) {
	return file_protocol_server_command_proto_rawDescGZIP(), []int{18}
}

func (x *UserApprove) GetApproved() bool {
	if x != nil {
		return x.Approved
	}
	return false
}

func (x *UserApprove) GetApprovedBy() string {
	if x != nil {
		return x.ApprovedBy
	}
	return ""
}

func (x *UserApprove) GetApprovedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ApprovedAt
	}
	return nil
}

type ListUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersResponse) Reset() {
	*x = ListUsersResponse{}
	mi := &file_protocol_server_command_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersResponse) ProtoMessage() {}

func (x *ListUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_server_command_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersResponse.ProtoReflect.Descriptor instead.
func (*ListUsersResponse) Descriptor() ([]byte, []int) {
	return file_protocol_server_command_proto_rawDescGZIP(), []int{19}
}

func (x *ListUsersResponse) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

type ApproveUserAccessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApproveUserAccessRequest) Reset() {
	*x = ApproveUserAccessRequest{}
	mi := &file_protocol_server_command_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveUserAccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveUserAccessRequest) ProtoMessage() {}

func (x *ApproveUserAccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_server_command_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveUserAccessRequest.ProtoReflect.Descriptor instead.
func (*ApproveUserAccessRequest) Descriptor() ([]byte, []int) {
	return file_protocol_server_command_proto_rawDescGZIP(), []int{20}
}

func (x *ApproveUserAccessRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

var File_protocol_server_command_proto protoreflect.FileDescriptor

const file_protocol_server_command_proto_rawDesc = "" +
	"\n" +
	"\x1dprotocol/server-command.proto\x12\bprotocol\x1a\x15protocol/models.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"M\n" +
	"\vInitRequest\x12\x1a\n" +
	"\bkeyParts\x18\x01 \x01(\rR\bkeyParts\x12\"\n" +
	"\fkeyThreshold\x18\x02 \x01(\rR\fkeyThreshold\"*\n" +
	"\fInitResponse\x12\x1a\n" +
	"\bkeyParts\x18\x01 \x03(\tR\bkeyParts\"6\n" +
	"\x0eIsInitResponse\x12$\n" +
	"\risInitialized\x18\x01 \x01(\bR\risInitialized\"[\n" +
	"\rUnsealRequest\x12\x18\n" +
	"\akeyPart\x18\x01 \x01(\tR\akeyPart\x120\n" +
	"\x13removeExistingParts\x18\x02 \x01(\bR\x13removeExistingParts\"\x10\n" +
	"\x0eUnsealResponse\"\xbf\x01\n" +
	"\x14CreateNetworkRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x125\n" +
	"\bduration\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\bduration\x12\x16\n" +
	"\x06groups\x18\x03 \x03(\tR\x06groups\x12\x10\n" +
	"\x03ips\x18\x04 \x03(\tR\x03ips\x12\x18\n" +
	"\asubnets\x18\x05 \x03(\tR\asubnets\x12\x18\n" +
	"\aipPools\x18\x06 \x03(\tR\aipPools\"D\n" +
	"\x15CreateNetworkResponse\x12+\n" +
	"\anetwork\x18\x01 \x01(\v2\x11.protocol.NetworkR\anetwork\"\x14\n" +
	"\x12ListNetworkRequest\"D\n" +
	"\x13ListNetworkResponse\x12-\n" +
	"\bnetworks\x18\x01 \x03(\v2\x11.protocol.NetworkR\bnetworks\"\xb2\x01\n" +
	"\aNetwork\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x125\n" +
	"\bduration\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\bduration\x12\x16\n" +
	"\x06groups\x18\x03 \x03(\tR\x06groups\x12\x10\n" +
	"\x03ips\x18\x04 \x03(\tR\x03ips\x12\x18\n" +
	"\asubnets\x18\x05 \x03(\tR\asubnets\x12\x18\n" +
	"\aipPools\x18\x06 \x03(\tR\aipPools\"N\n" +
	"(ListCertificateAuthorityByNetworkRequest\x12\"\n" +
	"\fnetworkNames\x18\x01 \x03(\tR\fnetworkNames\"\x83\x01\n" +
	")ListCertificateAuthorityByNetworkResponse\x12V\n" +
	"\x16certificateAuthorities\x18\x01 \x03(\v2\x1e.protocol.CertificateAuthorityR\x16certificateAuthorities\"?\n" +
	"#GetEnrollmentTokenForNetworkRequest\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\"P\n" +
	"$GetEnrollmentTokenForNetworkResponse\x12(\n" +
	"\x0fenrollmentToken\x18\x01 \x01(\tR\x0fenrollmentToken\"m\n" +
	"\x1eListEnrollmentRequestsResponse\x12K\n" +
	"\x12enrollmentRequests\x18\x01 \x03(\v2\x1b.protocol.EnrollmentRequestR\x12enrollmentRequests\"\xc9\x01\n" +
	"\x11EnrollmentRequest\x12,\n" +
	"\x11clientFingerprint\x18\x01 \x01(\tR\x11clientFingerprint\x124\n" +
	"\acreated\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\acreated\x12 \n" +
	"\vnetworkName\x18\x03 \x01(\tR\vnetworkName\x12\x1a\n" +
	"\bclientIP\x18\x04 \x01(\tR\bclientIP\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\"O\n" +
	"\x1fApproveEnrollmentRequestRequest\x12,\n" +
	"\x11clientFingerprint\x18\x01 \x01(\tR\x11clientFingerprint\"\xa7\x01\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x124\n" +
	"\acreated\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\acreated\x12/\n" +
	"\aapprove\x18\n" +
	" \x01(\v2\x15.protocol.UserApproveR\aapprove\"\x85\x01\n" +
	"\vUserApprove\x12\x1a\n" +
	"\bapproved\x18\x01 \x01(\bR\bapproved\x12\x1e\n" +
	"\n" +
	"approvedBy\x18\x02 \x01(\tR\n" +
	"approvedBy\x12:\n" +
	"\n" +
	"approvedAt\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"approvedAt\"9\n" +
	"\x11ListUsersResponse\x12$\n" +
	"\x05users\x18\x01 \x03(\v2\x0e.protocol.UserR\x05users\"2\n" +
	"\x18ApproveUserAccessRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId2\xe1\a\n" +
	"\rServerCommand\x12<\n" +
	"\x06IsInit\x12\x16.google.protobuf.Empty\x1a\x18.protocol.IsInitResponse\"\x00\x127\n" +
	"\x04Init\x12\x15.protocol.InitRequest\x1a\x16.protocol.InitResponse\"\x00\x12=\n" +
	"\x06Unseal\x12\x17.protocol.UnsealRequest\x1a\x18.protocol.UnsealResponse\"\x00\x12R\n" +
	"\rCreateNetwork\x12\x1e.protocol.CreateNetworkRequest\x1a\x1f.protocol.CreateNetworkResponse\"\x00\x12L\n" +
	"\vListNetwork\x12\x1c.protocol.ListNetworkRequest\x1a\x1d.protocol.ListNetworkResponse\"\x00\x12\x8e\x01\n" +
	"!ListCertificateAuthorityByNetwork\x122.protocol.ListCertificateAuthorityByNetworkRequest\x1a3.protocol.ListCertificateAuthorityByNetworkResponse\"\x00\x12\x7f\n" +
	"\x1cGetEnrollmentTokenForNetwork\x12-.protocol.GetEnrollmentTokenForNetworkRequest\x1a..protocol.GetEnrollmentTokenForNetworkResponse\"\x00\x12\\\n" +
	"\x16ListEnrollmentRequests\x12\x16.google.protobuf.Empty\x1a(.protocol.ListEnrollmentRequestsResponse\"\x00\x12_\n" +
	"\x18ApproveEnrollmentRequest\x12).protocol.ApproveEnrollmentRequestRequest\x1a\x16.google.protobuf.Empty\"\x00\x12T\n" +
	"\x1bListUsersWaitingForApproval\x12\x16.google.protobuf.Empty\x1a\x1b.protocol.ListUsersResponse\"\x00\x12Q\n" +
	"\x11ApproveUserAccess\x12\".protocol.ApproveUserAccessRequest\x1a\x16.google.protobuf.Empty\"\x00B\x8f\x01\n" +
	"\fcom.protocolB\x12ServerCommandProtoP\x01Z+github.com/cego/nebula-provisioner/protocol\xa2\x02\x03PXX\xaa\x02\bProtocol\xca\x02\bProtocol\xe2\x02\x14Protocol\\GPBMetadata\xea\x02\bProtocolb\x06proto3"

var (
	file_protocol_server_command_proto_rawDescOnce sync.Once
	file_protocol_server_command_proto_rawDescData []byte
)

func file_protocol_server_command_proto_rawDescGZIP() []byte {
	file_protocol_server_command_proto_rawDescOnce.Do(func() {
		file_protocol_server_command_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protocol_server_command_proto_rawDesc), len(file_protocol_server_command_proto_rawDesc)))
	})
	return file_protocol_server_command_proto_rawDescData
}

var file_protocol_server_command_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_protocol_server_command_proto_goTypes = []any{
	(*InitRequest)(nil),                               // 0: protocol.InitRequest
	(*InitResponse)(nil),                              // 1: protocol.InitResponse
	(*IsInitResponse)(nil),                            // 2: protocol.IsInitResponse
	(*UnsealRequest)(nil),                             // 3: protocol.UnsealRequest
	(*UnsealResponse)(nil),                            // 4: protocol.UnsealResponse
	(*CreateNetworkRequest)(nil),                      // 5: protocol.CreateNetworkRequest
	(*CreateNetworkResponse)(nil),                     // 6: protocol.CreateNetworkResponse
	(*ListNetworkRequest)(nil),                        // 7: protocol.ListNetworkRequest
	(*ListNetworkResponse)(nil),                       // 8: protocol.ListNetworkResponse
	(*Network)(nil),                                   // 9: protocol.Network
	(*ListCertificateAuthorityByNetworkRequest)(nil),  // 10: protocol.ListCertificateAuthorityByNetworkRequest
	(*ListCertificateAuthorityByNetworkResponse)(nil), // 11: protocol.ListCertificateAuthorityByNetworkResponse
	(*GetEnrollmentTokenForNetworkRequest)(nil),       // 12: protocol.GetEnrollmentTokenForNetworkRequest
	(*GetEnrollmentTokenForNetworkResponse)(nil),      // 13: protocol.GetEnrollmentTokenForNetworkResponse
	(*ListEnrollmentRequestsResponse)(nil),            // 14: protocol.ListEnrollmentRequestsResponse
	(*EnrollmentRequest)(nil),                         // 15: protocol.EnrollmentRequest
	(*ApproveEnrollmentRequestRequest)(nil),           // 16: protocol.ApproveEnrollmentRequestRequest
	(*User)(nil),                                      // 17: protocol.User
	(*UserApprove)(nil),                               // 18: protocol.UserApprove
	(*ListUsersResponse)(nil),                         // 19: protocol.ListUsersResponse
	(*ApproveUserAccessRequest)(nil),                  // 20: protocol.ApproveUserAccessRequest
	(*durationpb.Duration)(nil),                       // 21: google.protobuf.Duration
	(*CertificateAuthority)(nil),                      // 22: protocol.CertificateAuthority
	(*timestamppb.Timestamp)(nil),                     // 23: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                             // 24: google.protobuf.Empty
}
var file_protocol_server_command_proto_depIdxs = []int32{
	21, // 0: protocol.CreateNetworkRequest.duration:type_name -> google.protobuf.Duration
	9,  // 1: protocol.CreateNetworkResponse.network:type_name -> protocol.Network
	9,  // 2: protocol.ListNetworkResponse.networks:type_name -> protocol.Network
	21, // 3: protocol.Network.duration:type_name -> google.protobuf.Duration
	22, // 4: protocol.ListCertificateAuthorityByNetworkResponse.certificateAuthorities:type_name -> protocol.CertificateAuthority
	15, // 5: protocol.ListEnrollmentRequestsResponse.enrollmentRequests:type_name -> protocol.EnrollmentRequest
	23, // 6: protocol.EnrollmentRequest.created:type_name -> google.protobuf.Timestamp
	23, // 7: protocol.User.created:type_name -> google.protobuf.Timestamp
	18, // 8: protocol.User.approve:type_name -> protocol.UserApprove
	23, // 9: protocol.UserApprove.approvedAt:type_name -> google.protobuf.Timestamp
	17, // 10: protocol.ListUsersResponse.users:type_name -> protocol.User
	24, // 11: protocol.ServerCommand.IsInit:input_type -> google.protobuf.Empty
	0,  // 12: protocol.ServerCommand.Init:input_type -> protocol.InitRequest
	3,  // 13: protocol.ServerCommand.Unseal:input_type -> protocol.UnsealRequest
	5,  // 14: protocol.ServerCommand.CreateNetwork:input_type -> protocol.CreateNetworkRequest
	7,  // 15: protocol.ServerCommand.ListNetwork:input_type -> protocol.ListNetworkRequest
	10, // 16: protocol.ServerCommand.ListCertificateAuthorityByNetwork:input_type -> protocol.ListCertificateAuthorityByNetworkRequest
	12, // 17: protocol.ServerCommand.GetEnrollmentTokenForNetwork:input_type -> protocol.GetEnrollmentTokenForNetworkRequest
	24, // 18: protocol.ServerCommand.ListEnrollmentRequests:input_type -> google.protobuf.Empty
	16, // 19: protocol.ServerCommand.ApproveEnrollmentRequest:input_type -> protocol.ApproveEnrollmentRequestRequest
	24, // 20: protocol.ServerCommand.ListUsersWaitingForApproval:input_type -> google.protobuf.Empty
	20, // 21: protocol.ServerCommand.ApproveUserAccess:input_type -> protocol.ApproveUserAccessRequest
	2,  // 22: protocol.ServerCommand.IsInit:output_type -> protocol.IsInitResponse
	1,  // 23: protocol.ServerCommand.Init:output_type -> protocol.InitResponse
	4,  // 24: protocol.ServerCommand.Unseal:output_type -> protocol.UnsealResponse
	6,  // 25: protocol.ServerCommand.CreateNetwork:output_type -> protocol.CreateNetworkResponse
	8,  // 26: protocol.ServerCommand.ListNetwork:output_type -> protocol.ListNetworkResponse
	11, // 27: protocol.ServerCommand.ListCertificateAuthorityByNetwork:output_type -> protocol.ListCertificateAuthorityByNetworkResponse
	13, // 28: protocol.ServerCommand.GetEnrollmentTokenForNetwork:output_type -> protocol.GetEnrollmentTokenForNetworkResponse
	14, // 29: protocol.ServerCommand.ListEnrollmentRequests:output_type -> protocol.ListEnrollmentRequestsResponse
	24, // 30: protocol.ServerCommand.ApproveEnrollmentRequest:output_type -> google.protobuf.Empty
	19, // 31: protocol.ServerCommand.ListUsersWaitingForApproval:output_type -> protocol.ListUsersResponse
	24, // 32: protocol.ServerCommand.ApproveUserAccess:output_type -> google.protobuf.Empty
	22, // [22:33] is the sub-list for method output_type
	11, // [11:22] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_protocol_server_command_proto_init() }
func file_protocol_server_command_proto_init() {
	if File_protocol_server_command_proto != nil {
		return
	}
	file_protocol_models_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protocol_server_command_proto_rawDesc), len(file_protocol_server_command_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protocol_server_command_proto_goTypes,
		DependencyIndexes: file_protocol_server_command_proto_depIdxs,
		MessageInfos:      file_protocol_server_command_proto_msgTypes,
	}.Build()
	File_protocol_server_command_proto = out.File
	file_protocol_server_command_proto_goTypes = nil
	file_protocol_server_command_proto_depIdxs = nil
}
