// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Agent struct {
	ClientFingerprint string    `json:"clientFingerprint"`
	Created           string    `json:"created"`
	NetworkName       string    `json:"networkName"`
	Groups            []*string `json:"groups"`
	AssignedIP        *string   `json:"assignedIP"`
	IssuedAt          *string   `json:"issuedAt"`
	ExpiresAt         *string   `json:"expiresAt"`
	Name              *string   `json:"name"`
}

type EnrollmentRequest struct {
	ClientFingerprint string  `json:"clientFingerprint"`
	Created           string  `json:"created"`
	NetworkName       string  `json:"networkName"`
	ClientIP          *string `json:"clientIP"`
	Name              *string `json:"name"`
}

type Network struct {
	Name               string               `json:"name"`
	Duration           *string              `json:"duration"`
	Groups             []*string            `json:"groups"`
	Ips                []*string            `json:"ips"`
	Subnets            []*string            `json:"subnets"`
	IPPools            []*string            `json:"ipPools"`
	Agents             []*Agent             `json:"agents"`
	EnrollmentToken    *string              `json:"enrollmentToken"`
	EnrollmentRequests []*EnrollmentRequest `json:"enrollmentRequests"`
}

type User struct {
	ID          string       `json:"id"`
	Name        string       `json:"name"`
	Email       string       `json:"email"`
	UserApprove *UserApprove `json:"userApprove"`
	Disabled    bool         `json:"disabled"`
}

type UserApprove struct {
	Approved       bool   `json:"approved"`
	ApprovedBy     string `json:"approvedBy"`
	ApprovedByUser *User  `json:"approvedByUser"`
	ApprovedAt     string `json:"approvedAt"`
}
